export const GET_ALL_INTERFACE = 'GET_ALL_INTERFACE';
export const ADD_NEW_INTERFACE='ADD_NEW_INTERFACE'
export const GET_INTERFACE_BY_ID='GET_INTERFACE_BY_ID'
export const DELETE_INTERFACE='DELETE_INTERFACE'
export const EDIT_INTERFACE='EDIT_INTERFACE'
export const GET_ETAPES_BY_WORKFLOW='GET_ETAPES_BY_WORKFLOW'
