export const SHOW_ASIDE_ADD_MODE_INTERFACE = "SHOW_ASIDE_ADD_MODE_INTERFACE";
export const CLOSE_ASIDE_INTERFACE = "CLOSE_ASIDE_INTERFACE";
export const RESET_ASIDE_INTERFACE = "RESET_ASIDE_INTERFACE";
export const SHOW_ASIDE_EDIT_MODE_INTERFACE = "SHOW_ASIDE_EDIT_MODE_INTERFACE";
export const SHOW_ASIDE_DELETE_MODE_INTERFACE = "SHOW_ASIDE_DELETE_MODE_INTERFACE";
export const SHOW_ASIDE_CONSULT_MODE_INTERFACE="SHOW_ASIDE_CONSULT_MODE_INTERFACE";
export const SHOW_MODAL_CONFIRMATION_INTERFACE="SHOW_MODAL_CONFIRMATION_INTERFACE";
export const CLOSE_MODAL_CONFIRMATION_INTERFACE="CLOSE_MODAL_CONFIRMATION_INTERFACE";
