export const CHECK_EMPLOYEE_EXISTENCE_REQUEST = 'CHECK_EMPLOYEE_EXISTENCE_REQUEST';
export const CHECK_EMPLOYEE_EXISTENCE_SUCCESS = 'CHECK_EMPLOYEE_EXISTENCE_SUCCESS';
export const CHECK_EMPLOYEE_EXISTENCE_FAILURE = 'CHECK_EMPLOYEE_EXISTENCE_FAILURE';