export const GET_ALL_EMPLOYEE = 'GET_ALL_EMPLOYEE';
export const ADD_NEW_EMPLOYEE='ADD_NEW_EMPLOYEE'
export const GET_EMPLOYEE_BY_ID='GET_EMPLOYEE_BY_ID'
export const DELETE_EMPLOYEE='DELETE_EMPLOYEE'
export const EDIT_EMPLOYEE='EDIT_EMPLOYEE'
