
export const CLOSE_ASIDE_DEMAND = "CLOSE_ASIDE_DEMAND";
export const RESET_ASIDE_DEMAND = "RESET_ASIDE_DEMAND";
export const SHOW_ASIDE_DELETE_MODE_DEMAND = "SHOW_ASIDE_DELETE_MODE_DEMAND";
export const SHOW_ASIDE_CONSULT_MODE_DEMAND="SHOW_ASIDE_CONSULT_MODE_DEMAND";
export const SHOW_MODAL_CONFIRMATION_DEMAND="SHOW_MODAL_CONFIRMATION_DEMAND";
export const CLOSE_MODAL_CONFIRMATION_DEMAND="CLOSE_MODAL_CONFIRMATION_DEMAND";