export const GET_ALL_DEMAND = 'GET_ALL_DEMAND';
export const ADD_NEW_DEMAND='ADD_NEW_DEMAND'
export const GET_DEMAND_BY_ID='GET_DEMAND_BY_ID'
export const DELETE_DEMAND='DELETE_DEMAND'
export const EDIT_DEMAND='EDIT_DEMAND'
export const GET_TICKET_DATA = 'GET_TICKET_DATA';
export const CLEAR_TICKET_DATA = 'CLEAR_TICKET_DATA';
