export const GET_ALL_MYDEMAND = 'GET_ALL_MYDEMAND';
export const ADD_NEW_MYDEMAND='ADD_NEW_MYDEMAND'
export const GET_MYDEMAND_BY_ID='GET_MYDEMAND_BY_ID'
export const DELETE_MYDEMAND='DELETE_MYDEMAND'
export const EDIT_MYDEMAND='EDIT_MYDEMAND'
export const GET_VALIDATION_BY_DEMAND='GET_VALIDATION_BY_DEMAND'