export const SHOW_ASIDE_ADD_MODE_MYDEMAND = "SHOW_ASIDE_ADD_MODE_MYDEMAND";
export const CLOSE_ASIDE_MYDEMAND = "CLOSE_ASIDE_MYDEMAND";
export const RESET_ASIDE_MYDEMAND = "RESET_ASIDE_MYDEMAND";
export const SHOW_ASIDE_EDIT_MODE_MYDEMAND = "SHOW_ASIDE_EDIT_MODE_MYDEMAND";
export const SHOW_ASIDE_DELETE_MODE_MYDEMAND = "SHOW_ASIDE_DELETE_MODE_MYDEMAND";
export const SHOW_ASIDE_CONSULT_MODE_MYDEMAND="SHOW_ASIDE_CONSULT_MODE_MYDEMAND";
export const SHOW_MODAL_CONFIRMATION_MYDEMAND="SHOW_MODAL_CONFIRMATION_MYDEMAND";
export const CLOSE_MODAL_CONFIRMATION_MYDEMAND="CLOSE_MODAL_CONFIRMATION_MYDEMAND";
