export const GET_ALL_WORKFLOW = 'GET_ALL_WORKFLOW';
export const ADD_NEW_WORKFLOW='ADD_NEW_WORKFLOW'
export const GET_WORKFLOW_BY_ID='GET_WORKFLOW_BY_ID'
export const DELETE_WORKFLOW='DELETE_WORKFLOW'
export const EDIT_WORKFLOW='EDIT_WORKFLOW'
