export const SHOW_ASIDE_ADD_MODE_WORKFLOW = "SHOW_ASIDE_ADD_MODE_WORKFLOW";
export const CLOSE_ASIDE_WORKFLOW = "CLOSE_ASIDE_WORKFLOW";
export const RESET_ASIDE_WORKFLOW = "RESET_ASIDE_WORKFLOW";
export const SHOW_ASIDE_EDIT_MODE_WORKFLOW = "SHOW_ASIDE_EDIT_MODE_WORKFLOW";
export const SHOW_ASIDE_DELETE_MODE_WORKFLOW = "SHOW_ASIDE_DELETE_MODE_WORKFLOW";
export const SHOW_ASIDE_CONSULT_MODE_WORKFLOW="SHOW_ASIDE_CONSULT_MODE_WORKFLOW";
export const SHOW_MODAL_CONFIRMATION_WORKFLOW="SHOW_MODAL_CONFIRMATION_WORKFLOW";
export const CLOSE_MODAL_CONFIRMATION_WORKFLOW="CLOSE_MODAL_CONFIRMATION_WORKFLOW";