export const SHOW_ASIDE_ADD_MODE_EQUIPE = "SHOW_ASIDE_ADD_MODE_EQUIPE";
export const CLOSE_ASIDE_EQUIPE = "CLOSE_ASIDE_EQUIPE";
export const RESET_ASIDE_EQUIPE = "RESET_ASIDE_EQUIPE";
export const SHOW_ASIDE_EDIT_MODE_EQUIPE = "SHOW_ASIDE_EDIT_MODE_EQUIPE";
export const SHOW_ASIDE_DELETE_MODE_EQUIPE = "SHOW_ASIDE_DELETE_MODE_EQUIPE";
export const SHOW_ASIDE_CONSULT_MODE_EQUIPE="SHOW_ASIDE_CONSULT_MODE_EQUIPE";
export const SHOW_MODAL_CONFIRMATION_EQUIPE="SHOW_MODAL_CONFIRMATION_EQUIPE";
export const CLOSE_MODAL_CONFIRMATION_EQUIPE="CLOSE_MODAL_CONFIRMATION_EQUIPE";

