
export const ADD_NEW_EQUIPE='ADD_NEW_EQUIPE'
export const GET_EQUIPE_BY_ID='GET_EQUIPE_BY_ID'
export const DELETE_EQUIPE='DELETE_EQUIPE'
export const EDIT_EQUIPE='EDIT_EQUIPE'
export const FETCH_EMPLOYEES_AND_ROLES_REQUEST = 'FETCH_EMPLOYEES_AND_ROLES_REQUEST';
export const FETCH_EMPLOYEES_AND_ROLES_SUCCESS = 'FETCH_EMPLOYEES_AND_ROLES_SUCCESS';
export const FETCH_EMPLOYEES_AND_ROLES_FAILURE = 'FETCH_EMPLOYEES_AND_ROLES_FAILURE';
export const GET_ALL_EMPLOYE = 'GET_ALL_EMPLOYE';
export const GET_ALL_ROLE = 'GET_ALL_ROLE';
